# Generated by Django 4.2 on 2023-04-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperLib',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Lp', models.IntegerField()),
                ('Nr', models.IntegerField()),
                ('Data', models.DateField()),
                ('Dzial', models.CharField(max_length=100)),
                ('Artykol', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=100)),
                ('Uwagi', models.CharField(max_length=150)),
            ],
        ),
    ]
