# Generated by Django 4.2 on 2023-05-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonpaperlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Czasopismo', models.CharField(max_length=100)),
                ('Nr', models.IntegerField()),
                ('Data', models.DateField()),
                ('Dzial', models.CharField(max_length=100)),
                ('Artykol', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=100)),
                ('Uwagi', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='PaperLib',
        ),
    ]
